name: aashna
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Add the flutter_vision and camera dependencies
  flutter_vision: ^1.1.4 
   # replace with the latest version
  camera: ^0.10.0+4 # replace with the latest version
  flutter_tts: ^3.5.3 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/labels.txt
    - assets/yolov8n.tflite
